baseurl: /Notes
title: Bryan's Notes
subtitle: Notes
author: Bryan Gass
simple_search: http://google.com/search
description: A place where I store helpful resources and my notes from various classes I have taken
name: Bryan Gass's Notes

repository: BeeGass/Notes
github_username: BeeGass

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
